const Joi = require('joi');
const BaseModel = require('../utils/base-model.js');

//no id needed for user because it is generated by the server

const User = new BaseModel('User', {
  prenom: Joi.string().required(),
  nom: Joi.string().required(),
  identifiant: Joi.string().required(), // id to log in
  motDePasse: Joi.string().required(),
  status: Joi.string().required(),
  id: Joi.string().required(),
});

const TimeToAnswer = new BaseModel('TimeToAnswer', {
  id: Joi.string().required(), // id of the subQuizz
  time: Joi.date().required(), // time to answer
});

module.exports = {
  User,
  TimeToAnswer,
};
