version: "2.4"
services:
  front-end:
    build: 
      context: ./../front-end
      args: 
       - PROD_URL=http://localhost:8000
       - ENV=e2e
       - TEST_URL= http://localhost:8500
    image: front-end:test3.0
    ports:
      - "8580:80"
    healthcheck:
          test: [ "CMD-SHELL", "curl -f http://localhost:8580/ || exit 1" ]
          interval: 30s
          timeout: 10s
          retries: 3
    depends_on:
      - back-end
  back-end:
    build: 
      context: ./../back-end
      args: 
        - ENV=start:e2e

    image: back-end:test3.0
    ports:
      - "8500:9428"
    volumes:
      - ./../back-end/database:/app/database:rw
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8500/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  playwright:
    image: playwright:9.9.9
    ports:
      - 9323:9323
    depends_on:
      - front-end
    volumes:
      - ./../front-end/playwright-report:/app/playwright-report:rw
    build:
      context: ./../front-end/
      dockerfile: Dockerfile-e2e
    environment:
      - FRONT_URL=http://front-end  
